apiVersion: v1
kind: Service
metadata:
  name: game-frontend-service
  namespace: blindtest
  labels:
    app: game-frontend
spec:
  type: ClusterIP
  selector:
    app: game-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
