apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: blindtest
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
