apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: blindtest
  labels:
    app: mongo-express
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
