apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: blindtest
  labels:
    app: mongodb
type: Opaque
data:
  # Base64 encoded values:
  # admin -> YWRtaW4=
  # blindtest123 -> YmxpbmR0ZXN0MTIz
  # mongodb://admin:blindtest123@mongodb-service:27017/blindtest?authSource=admin -> bW9uZ29kYjovL2FkbWluOmJsaW5kdGVzdDEyM0Btb25nb2RiLXNlcnZpY2U6MjcwMTcvYmxpbmR0ZXN0P2F1dGhTb3VyY2U9YWRtaW4=
  MONGODB_USERNAME: YWRtaW4=
  MONGODB_PASSWORD: YmxpbmR0ZXN0MTIz
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOmJsaW5kdGVzdDEyM0Btb25nb2RiLXNlcnZpY2U6MjcwMTcvYmxpbmR0ZXN0P2F1dGhTb3VyY2U9YWRtaW4=
